### PR TITLE
LPS-80949 Portlet namespace prefix might be part of the attribute name when copying request attributes from HeaderRequest to RenderRequest

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@shuyangzhou 

- I saw the `NoClassDefFoundError` in two other pull requests today, so it must be unrelated. 

- I also saw the The functional-tomcat90-mysql57-jdk8/1 `NoSuchResourcePermissionException` failure in https://github.com/shuyangzhou/liferay-portal/pull/6463 so it must be unrelated.

Please review when you get an opportunity, thanks.
